# Generated by Django 6.0.3 on 2026-06-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff')], db_index=True, default='staff', max_length=10),
        ),
    ]
