# Generated by Django 6.0.3 on 2026-06-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_product_rights',
            field=models.BooleanField(default=False),
        ),
    ]
