# Generated by Django 6.0.3

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    User = apps.get_model('users', 'User')
    if not User.objects.filter(username='admin').exists():
        admin_user = User(
            username='admin',
            email='admin@example.com',
            is_staff=True,
            is_superuser=True,
            role='owner',
            employee_id='AR0001',
            password=make_password('Praveen@123')
        )
        admin_user.save()

def remove_superuser(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(username='admin').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_has_product_rights'),
    ]

    operations = [
        migrations.RunPython(create_superuser, reverse_code=remove_superuser),
    ]
