# Generated by Django 6.0.3 on 2026-06-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_address_user_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_bill_edit_rights',
            field=models.BooleanField(default=False),
        ),
    ]
