# Generated by Django 6.0.3 on 2026-06-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_has_bill_edit_rights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Admin'), ('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('staff', 'Staff')], db_index=True, default='staff', max_length=20),
        ),
    ]
