# Generated by Django 6.0.3 on 2026-06-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
