# Generated by Django 6.0.3 on 2026-07-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_attendance_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_pos_access',
            field=models.BooleanField(default=True),
        ),
    ]
