# Generated by Django 6.0.3 on 2026-07-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_has_attendance_access_user_has_pos_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Admin'), ('regional_manager', 'Regional Manager'), ('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('sales_staff', 'Sales Staff')], db_index=True, default='sales_staff', max_length=20),
        ),
    ]
