# Generated by Django 6.0.3 on 2026-07-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.SlugField(blank=True, unique=True)),
                ('has_pos_access', models.BooleanField(default=True)),
                ('has_attendance_access', models.BooleanField(default=True)),
                ('has_all_branches_access', models.BooleanField(default=False)),
                ('has_product_rights', models.BooleanField(default=False)),
                ('has_bill_edit_rights', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Admin'), ('regional_manager', 'Regional Manager'), ('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('sales_staff', 'Sales Staff')], db_index=True, default='sales_staff', max_length=50),
        ),
    ]
