# Generated by Django 6.0.3 on 2026-07-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_customrole_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grace_period_minutes',
            field=models.IntegerField(default=15, help_text='Grace period in minutes before marked Late'),
        ),
        migrations.AddField(
            model_name='user',
            name='shift_end_time',
            field=models.TimeField(default='17:00:00', help_text='Shift end time'),
        ),
        migrations.AddField(
            model_name='user',
            name='shift_start_time',
            field=models.TimeField(default='09:00:00', help_text='Shift start time'),
        ),
    ]
