# Generated by Django 6.0.3 on 2026-08-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_grace_period_minutes_user_shift_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleShiftPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=50, unique=True)),
                ('role_name', models.CharField(blank=True, max_length=100)),
                ('shift_start_time', models.TimeField(default='09:00:00')),
                ('shift_end_time', models.TimeField(default='17:00:00')),
                ('weekly_off_day', models.CharField(default='Sunday', max_length=50)),
                ('monthly_off_count', models.IntegerField(default=4, help_text='Number of monthly week-offs allowed for this role')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_off_count',
            field=models.IntegerField(default=4, help_text='Monthly week offs count'),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_off_day',
            field=models.CharField(default='Sunday', help_text='Weekly off day based on role', max_length=50),
        ),
    ]
