# Generated by Django 6.0.3 on 2026-08-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_roleshiftpolicy_user_monthly_off_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleshiftpolicy',
            name='weekly_off_day',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weekly_off_day',
        ),
    ]
