# Generated by Django 6.0.3 on 2026-08-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_roleshiftpolicy_weekly_off_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(db_index=True, default='sales_staff', max_length=50),
        ),
    ]
