# Generated by Django 6.0.3 on 2026-08-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrole',
            name='dashboard_access',
            field=models.CharField(default='manager', help_text='Dashboard level: owner, manager, or staff', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='dashboard_access',
            field=models.CharField(default='staff', help_text='Dashboard level: owner, manager, or staff', max_length=20),
        ),
    ]
