# Generated by Django 6.0.3 on 2026-08-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_customrole_dashboard_access_user_dashboard_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roleshiftpolicy',
            options={'ordering': ['id']},
        ),
    ]
