# Generated by Django 6.0.3 on 2026-03-25 10:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_bill_id_alter_billitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='share_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
