# Generated by Django 6.0.3 on 2026-04-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_bill_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='online_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('split', 'Split Payment')], default='cash', max_length=10),
        ),
    ]
