# Generated by Django 6.0.3 on 2026-04-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_bill_cash_amount_bill_online_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
