# Generated by Django 6.0.3 on 2026-05-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_bill_id_alter_billitem_id_alter_creditnote_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
