# Generated by Django 6.0.3 on 2026-05-31 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_bill_invoice_number_bill_sequence_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='bill_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billitem'),
        ),
    ]
