# Generated by Django 6.0.3 on 2026-05-31 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_alter_returnrequest_bill_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='bill_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to='billing.billitem'),
        ),
    ]
