# Generated by Django 6.0.3 on 2026-06-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_alter_bill_cash_amount_alter_bill_discount_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='discount_amount',
            new_name='retail_price',
        ),
    ]
