# Generated by Django 6.0.3 on 2026-06-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_rename_discount_amount_bill_retail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='exchange_from',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
