# Generated by Django 6.0.3 on 2026-06-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_billitem_exchange_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='action_type',
            field=models.CharField(choices=[('REFUND', 'Refund'), ('EXCHANGE', 'Exchange'), ('EXCH_SAME', 'Exchange with same item (Another one)'), ('EXCH_NEW', 'Exchange with new item (Different product)')], default='REFUND', max_length=10),
        ),
    ]
