# Generated by Django 6.0.3 on 2026-06-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_alter_returnrequest_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='action_type',
            field=models.CharField(choices=[('REFUND', 'Refund'), ('EXCHANGE', 'Exchange'), ('EXCH_SAME', 'Exchange with same item (Another one)')], default='REFUND', max_length=10),
        ),
    ]
