# Generated by Django 6.0.3 on 2026-06-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_alter_returnrequest_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='edit_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
