# Generated by Django 6.0.3 on 2026-06-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_bill_edit_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='edit_reason',
        ),
    ]
