# Generated by Django 6.0.3 on 2026-06-18 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_alter_bill_created_at'),
        ('core', '0030_alter_stockadjustment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='has_returns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='price_difference',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='replacement_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_returns', to='core.product'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='replacement_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='action_type',
            field=models.CharField(choices=[('REFUND', 'Refund'), ('EXCHANGE', 'Exchange'), ('EXCH_SAME', 'Exchange with same item (Another one)')], default='EXCHANGE', max_length=10),
        ),
    ]
