# Generated by Django 6.0.3 on 2026-06-24 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_bill_has_returns_billitem_returned_quantity_and_more'),
        ('core', '0031_alter_productregistry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the target month (e.g., 2026-06-01)')),
                ('target_sales', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.branch')),
            ],
            options={
                'unique_together': {('branch', 'month')},
            },
        ),
    ]
