# Generated by Django 6.0.3 on 2026-06-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_branchgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='online_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('split', 'Split Payment')], default='cash', max_length=10),
        ),
    ]
