# Generated by Django 6.0.3 on 2026-07-22 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_returnrequest_cash_amount_and_more'),
        ('core', '0031_alter_productregistry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='combo_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='core.combogroup'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='action_type',
            field=models.CharField(choices=[('REFUND', 'Refund'), ('EXCHANGE', 'Exchange'), ('EXCH_SAME', 'Exchange with same item')], default='EXCHANGE', max_length=10),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='condition',
            field=models.CharField(choices=[('GOOD', 'Good - Resellable'), ('DAMAGED', 'Damaged')], default='GOOD', max_length=10),
        ),
    ]
