# Generated by Django 6.0.3 on 2026-04-10 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_id_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'verbose_name_plural': 'Product Registries',
                'unique_together': {('branch', 'product')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='branches',
            field=models.ManyToManyField(related_name='products', through='core.ProductRegistry', to='core.branch'),
        ),
    ]
