# Generated by Django 6.0.3 on 2026-05-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_branch_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out (Sale)'), ('ADJ', 'Adjustment'), ('DMG', 'Damaged')], max_length=5),
        ),
    ]
