# Generated by Django 6.0.3 on 2026-05-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
