# Generated by Django 6.0.3 on 2026-06-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_branch_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productregistry',
            name='low_stock_threshold',
        ),
        migrations.AddField(
            model_name='productregistry',
            name='damaged_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
