# Generated by Django 6.0.3 on 2026-06-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_branch_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='invoice_prefix',
            field=models.CharField(default='AG', help_text="Prefix for invoice numbers (e.g., 'AG')", max_length=10, unique=True),
        ),
    ]
