# Generated by Django 6.0.3 on 2026-06-10 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_branch_invoice_prefix'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comboprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comboprice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='core.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='comboprice',
            unique_together={('product', 'branch', 'quantity')},
        ),
    ]
