# Generated by Django 6.0.3 on 2026-06-10 12:26

from django.db import migrations

def migrate_combos(apps, schema_editor):
    ComboPrice = apps.get_model('core', 'ComboPrice')
    ProductRegistry = apps.get_model('core', 'ProductRegistry')
    Branch = apps.get_model('core', 'Branch')

    # Find combos that have no branch assigned
    combos_to_migrate = list(ComboPrice.objects.filter(branch__isnull=True))

    for combo in combos_to_migrate:
        # Find which branches this product is registered to
        registrations = ProductRegistry.objects.filter(product=combo.product)
        branches = [r.branch for r in registrations]

        if not branches:
            # Fallback: assign to the first branch in the system, if any exists
            first_branch = Branch.objects.first()
            if first_branch:
                combo.branch = first_branch
                combo.save()
        else:
            # Assign the first branch to the existing combo price record
            combo.branch = branches[0]
            combo.save()

            # Duplicate the combo price for any other branches where the product is registered
            for branch in branches[1:]:
                # Check if a combo price for this product, branch, and quantity already exists to prevent duplicate key errors
                if not ComboPrice.objects.filter(product=combo.product, branch=branch, quantity=combo.quantity).exists():
                    ComboPrice.objects.create(
                        product=combo.product,
                        branch=branch,
                        quantity=combo.quantity,
                        price=combo.price
                    )

def reverse_migrate_combos(apps, schema_editor):
    ComboPrice = apps.get_model('core', 'ComboPrice')
    seen = set()
    for combo in list(ComboPrice.objects.all()):
        key = (combo.product_id, combo.quantity)
        if key in seen:
            combo.delete()
        else:
            seen.add(key)
            combo.branch = None
            combo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_comboprice_unique_together_comboprice_branch_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_combos, reverse_code=reverse_migrate_combos),
    ]
