# Generated by Django 6.0.3 on 2026-06-10 12:37

from django.db import migrations

def migrate_products_to_branch_scoped(apps, schema_editor):
    Product = apps.get_model('core', 'Product')
    ProductRegistry = apps.get_model('core', 'ProductRegistry')
    StockTransaction = apps.get_model('core', 'StockTransaction')
    StockAdjustment = apps.get_model('core', 'StockAdjustment')
    ComboPrice = apps.get_model('core', 'ComboPrice')
    
    # Check if models from billing app are available, otherwise skip (some environments might load in chunks)
    try:
        BillItem = apps.get_model('billing', 'BillItem')
        ReturnRequest = apps.get_model('billing', 'ReturnRequest')
    except (LookupError, ValueError):
        BillItem = None
        ReturnRequest = None

    # Iterate over all registries
    for registry in list(ProductRegistry.objects.all()):
        product = registry.product
        branch = registry.branch

        if product.branch is None:
            # Set the branch on the existing product record
            product.branch = branch
            product.save()
        elif product.branch != branch:
            # This product is shared and already assigned to another branch. Duplicate it!
            new_product = Product.objects.create(
                name=product.name,
                barcode=product.barcode,
                price=product.price,
                size=product.size,
                branch=branch
            )
            # Update registry to point to the new product
            registry.product = new_product
            registry.save()

            # Update related StockTransaction records
            StockTransaction.objects.filter(product=product, branch=branch).update(product=new_product)

            # Update related StockAdjustment records
            StockAdjustment.objects.filter(product=product, branch=branch).update(product=new_product)

            # Update related ComboPrice records
            ComboPrice.objects.filter(product=product, branch=branch).update(product=new_product)

            # Update related BillItem records for bills of this branch
            if BillItem:
                BillItem.objects.filter(product=product, bill__branch=branch).update(product=new_product)

            # Update related ReturnRequest records for this branch
            if ReturnRequest:
                ReturnRequest.objects.filter(product=product, active_branch=branch).update(product=new_product)

def reverse_migrate_products_to_branch_scoped(apps, schema_editor):
    Product = apps.get_model('core', 'Product')
    ProductRegistry = apps.get_model('core', 'ProductRegistry')
    StockTransaction = apps.get_model('core', 'StockTransaction')
    StockAdjustment = apps.get_model('core', 'StockAdjustment')
    ComboPrice = apps.get_model('core', 'ComboPrice')
    
    try:
        BillItem = apps.get_model('billing', 'BillItem')
        ReturnRequest = apps.get_model('billing', 'ReturnRequest')
    except (LookupError, ValueError):
        BillItem = None
        ReturnRequest = None

    barcodes = list(Product.objects.values_list('barcode', flat=True).distinct())
    for barcode in barcodes:
        products_with_barcode = list(Product.objects.filter(barcode=barcode).order_by('id'))
        if len(products_with_barcode) > 1:
            primary_product = products_with_barcode[0]
            for dup_product in products_with_barcode[1:]:
                # Update all registries and relations to point to primary
                ProductRegistry.objects.filter(product=dup_product).update(product=primary_product)
                StockTransaction.objects.filter(product=dup_product).update(product=primary_product)
                StockAdjustment.objects.filter(product=dup_product).update(product=primary_product)
                ComboPrice.objects.filter(product=dup_product).update(product=primary_product)
                
                if BillItem:
                    BillItem.objects.filter(product=dup_product).update(product=primary_product)
                if ReturnRequest:
                    ReturnRequest.objects.filter(product=dup_product).update(product=primary_product)
                
                # Delete duplicate
                dup_product.delete()

    # Set branch to None on all remaining products
    Product.objects.all().update(branch=None)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_product_branch_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_products_to_branch_scoped, reverse_code=reverse_migrate_products_to_branch_scoped),
    ]
