# Generated by Django 6.0.3 on 2026-06-11 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_duplicate_shared_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Mix & Match Summer Promo', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(blank=True, related_name='combo_groups', to='core.branch')),
                ('products', models.ManyToManyField(blank=True, related_name='combo_groups', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ComboTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity milestone (e.g. 2, 5, 10)')),
                ('price', models.DecimalField(decimal_places=0, help_text='Special price for this quantity milestone', max_digits=12)),
                ('combo_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='core.combogroup')),
            ],
            options={
                'ordering': ['quantity'],
                'unique_together': {('combo_group', 'quantity')},
            },
        ),
    ]
