# Generated by Django 6.0.3 on 2026-06-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='combogroup',
            name='combo_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
