# Generated by Django 6.0.3 on 2026-06-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_combogroup_combo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combogroup',
            name='combo_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
