# Generated by Django 6.0.3 on 2026-06-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_stockadjustment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productregistry',
            options={'verbose_name': 'Branch-wise Product', 'verbose_name_plural': 'Branch-wise Products'},
        ),
    ]
