# Generated by Django 6.0.3 on 2026-04-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productregistry_product_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregistry',
            name='low_stock_threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='productregistry',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productregistry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
