# Generated by Django 6.0.3 on 2026-05-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_branch_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
    ]
