# Generated by Django 6.0.3 on 2026-05-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_branch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='invoice_prefix',
            field=models.CharField(default='AG', help_text="Prefix for invoice numbers (e.g., 'AG')", max_length=10),
        ),
    ]
