# Generated by Django 6.0.3 on 2026-06-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_productregistry_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregistry',
            name='low_stock_threshold',
            field=models.IntegerField(default=10),
        ),
    ]
