# Generated by Django 6.0.3 on 2026-06-03 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_product_combo_price_2_product_combo_price_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='combo_price_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='combo_price_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='combo_price_45',
        ),
        migrations.CreateModel(
            name='ComboPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of units in this combo')),
                ('price', models.DecimalField(decimal_places=2, help_text='Total price for the quantity', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='core.product')),
            ],
            options={
                'ordering': ['quantity'],
                'unique_together': {('product', 'quantity')},
            },
        ),
    ]
