# Generated by Django 6.0.3 on 2026-06-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_product_combo_price_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboprice',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Total price for the quantity', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
