# Generated by Django 6.0.3 on 2026-06-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_comboprice_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Adminpage', 'verbose_name_plural': 'Adminpage'},
        ),
    ]
