# Generated by Django 6.0.3 on 2026-07-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('emergency', 'Emergency Leave')], max_length=20),
        ),
    ]
