# Generated by Django 6.0.3 on 2026-07-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryconfig',
            name='max_hours_per_permission',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Maximum hours allowed per permission request', max_digits=4),
        ),
        migrations.AddField(
            model_name='salaryconfig',
            name='max_permissions_per_month',
            field=models.IntegerField(default=2, help_text='Maximum permission requests allowed per month'),
        ),
    ]
