# Generated by Django 6.0.3 on 2026-07-29 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_salaryconfig_max_hours_per_permission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPermissionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_permissions_per_month', models.IntegerField(default=2, help_text='Maximum permission requests allowed per month for all employees')),
                ('max_hours_per_permission', models.DecimalField(decimal_places=2, default=2.0, help_text='Maximum hours allowed per permission request for all employees', max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Permission Policy',
                'verbose_name_plural': 'Global Permission Policies',
            },
        ),
    ]
