# Generated by Django 6.0.3 on 2026-07-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_globalpermissionpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpermissionpolicy',
            name='late_threshold_for_half_day_deduction',
            field=models.IntegerField(default=4, help_text='Number of late check-ins per month that trigger half-day salary deduction'),
        ),
    ]
