# Generated by Django 6.0.3 on 2026-07-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_updated_at_attendance_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpermissionpolicy',
            name='grace_period_minutes',
            field=models.IntegerField(default=15, help_text='Global grace period in minutes before marked Late'),
        ),
    ]
