# Generated by Django 4.2.30 on 2026-08-13 08:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_globalpermissionpolicy_grace_period_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('on_leave', 'On Leave'), ('week_off', 'Week Off')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='absent_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='present_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5),
        ),
    ]
