# Generated by Django 4.2.30 on 2026-08-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceauditlog',
            name='new_check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceauditlog',
            name='new_check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceauditlog',
            name='old_check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceauditlog',
            name='old_check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('checked_in', 'Checked In'), ('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('on_leave', 'On Leave'), ('week_off', 'Week Off')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='globalpermissionpolicy',
            name='late_threshold_for_half_day_deduction',
            field=models.IntegerField(default=1, help_text='Number of late check-ins per month that trigger half-day salary deduction'),
        ),
    ]
